# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be8e535483942f25108673330da50aa92f6a5a20044a432dc11ad964f8e74282b78cc22188e1b41d1bff674eafbc3dc37af297066c13eee20ba0eaa7062acbef

test:
  secret_key_base: d2fcb8aec9b3191995ac11ef0e31cef700b061d0aab2d724254f779d291f752c60381dfeeb10fe47157ec6a09b8e9a0e7b3a9e3e113859904e038cab15f82148

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
